# Generated by Django 4.2.2 on 2023-06-27 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_cliente_detallepedido_producto_pedido_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
